//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertSolution.CW_Alerts_Noticeboard_Web_Part {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class CW_Alerts_Noticeboard_Web_Part {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "14.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(CW_Alerts_Noticeboard_Web_Part target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void @__BuildControlTree(global::AlertSolution.CW_Alerts_Noticeboard_Web_Part.CW_Alerts_Noticeboard_Web_Part @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"" +
                        "></script>\r\n<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/f" +
                        "ont-awesome.min.css\" rel=\"stylesheet\" />\r\n<link rel=\"stylesheet\" type=\"text/css\"" +
                        " href=\"/Style Library/custom/alerts-noticeboard.css\"/>\r\n\r\n<script>\r\n    function" +
                        " LoadAlertsNoticeboardContents() {\r\n\r\n        var siteUrl = _spPageContextInfo.w" +
                        "ebAbsoluteUrl;\r\n        var dateTxt = new Date().toISOString().substring(0, 10);" +
                        "\r\n        var modifyDate = dateTxt + \"T13:00:00Z\";\r\n        //console.log(modify" +
                        "Date);\r\n        //console.log(_spPageContextInfo);\r\n        //var urlForList = s" +
                        "iteUrl + \"/Lists/AlertsList/AllItems.aspx\";\r\n        $.ajax({\r\n            url: " +
                        "siteUrl + \"/_api/web/lists/getbytitle(\'Alerts Noticeboard\')/items?$filter=StartD" +
                        "ate lt datetime\'\" + modifyDate + \"\' and EndDate ge datetime\'\" + modifyDate + \"\'\"" +
                        ",\r\n            method: \"GET\",\r\n            headers: { \"Accept\": \"application/jso" +
                        "n; odata=verbose\" },\r\n            success: function (data) {\r\n                //" +
                        " Returning the results\r\n                var listItems = data.d.results;\r\n\r\n     " +
                        "           // Remove the placeholder as we have successfully looked for alerts\r\n" +
                        "                $(\'#coliban-alerts-loading-placeholder\').remove();\r\n\r\n          " +
                        "      for (i = 0; i < listItems.length; i++) {\r\n                    var alertDiv" +
                        " = \"<div class=\\\"alertDiv\\\"><div class=\\\"alertType \" + listItems[i].AlertType + " +
                        "\"\\\"><i class=\\\"fa fa-bell\\\" aria-hidden=\\\"true\\\"></i> alert<div class=\\\"alertAng" +
                        "le\\\"></div></div><div class=\\\"alertText\\\">\" + listItems[i].Title + \" <a href=\\\"h" +
                        "ttps://google.com\\\">Read More</a> </div></div>\";\r\n                    $(\"#alerts" +
                        "Space\").append(alertDiv);\r\n                }\r\n            },\r\n            error:" +
                        " function (data) {\r\n                $(\'#coliban-alerts-loading-placeholder\').htm" +
                        "l(\"<p>An error occurred whilst looking for alerts. Please ensure that you have e" +
                        "nabled the CW Alerts Management feature in your site\'s settings.</p>\");\r\n       " +
                        "     }\r\n        });\r\n    }\r\n\r\n    $(document).ready(LoadAlertsNoticeboardContent" +
                        "s());\r\n</script>\r\n\r\n\r\n\r\n<div id=\"alertsSpace\">\r\n    <span id=\"coliban-alerts-loa" +
                        "ding-placeholder\"><i class=\"fa fa-spinner fa-pulse fa-3x fa-fw\" aria-hidden=\"tru" +
                        "e\"></i> Looking for current alerts...</span>\r\n</div>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "14.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
